### ISSUE TITLE
Test with enzyme

### ISSUE THREAD

**Issue by andresgallego** [jshomes/course-player#2]
Eric, I found the solution for the error that you were getting when using enzyme for testing, you just need to wrap the `<h1 className="course-title">{ courseTitle }</h1>` inside a div element as follows:
`export default React => ({ courseTitle }) => (
  <div>
    <h1 className="course-title">{ courseTitle }</h1>
  </div>
);`

**Comment by ericelliott** [comment]
So, it's a bug in Enzyme that would require you to change the source code to work around it... that's a non-starter. =)

Thanks!
